### ISSUE TITLE
Lite logg tilgjengelig, riktig?

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-api-endpoints#7]
Svært lite tilgjengelig logg.
Utelukkende to linjer registrert på fire uker. Disse er tolket som warning, som er litt uvisst om stemmer.

**Comment by valosnah** [comment]
Logger oppstart korrekt, og det som tilsynelatende er warning-grade feilmeldinger som warnings. Kan lukkes.

**Comment by shenluna** [comment]
Verifisert av Hans Olav
